# Generated by Django 3.2.7 on 2021-10-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UtilidadesApp', '0002_equipamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='plantel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
