# Generated by Django 3.2.7 on 2021-10-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UtilidadesApp', '0003_plantel'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonados',
            name='direccion_abonado',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='abonados',
            name='nombre_abonado',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='abonados',
            name='numero_telefono',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='abonados',
            name='observacion_abonado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='nombre_equipamiento',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='ubicacion_puerto',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='plantel',
            name='condicion_plantel',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plantel',
            name='par_numero',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
