# Generated by Django 3.2.7 on 2021-10-22 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UtilidadesApp', '0004_auto_20211022_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantel',
            name='numero_telefono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UtilidadesApp.abonados'),
            preserve_default=False,
        ),
    ]
