# Generated by Django 3.2.7 on 2021-10-22 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UtilidadesApp', '0005_plantel_numero_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamiento',
            name='numero_telefono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UtilidadesApp.abonados'),
            preserve_default=False,
        ),
    ]
