# Generated by Django 3.2.7 on 2021-10-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UtilidadesApp', '0006_equipamiento_numero_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonados',
            name='id',
        ),
        migrations.AlterField(
            model_name='abonados',
            name='numero_telefono',
            field=models.CharField(default=1, max_length=6, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
