# Generated by Django 3.2.7 on 2021-10-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UtilidadesApp', '0007_auto_20211022_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonados',
            name='numero_telefono',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
